name: messit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  path_provider: ^2.1.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/breakfast.png
    - assets/lunch.png
    - assets/snacks.png
    - assets/dinner.png
    - assets/messitbg.png
    - assets/data/
    - assets/data/menu_data.json
    - assets/mens_hostel.png
    - assets/ladies_hostel.png

#  fonts:
#    - family: PlusJakartaSans
#      fonts:
#        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
#        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
#          weight: 700
